### PR TITLE
Added vidx2pidx and PackIndex.xsd

### PR DESCRIPTION
**Pull request by soumeh01**
Addressing: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/163

### CODE REVIEW

**Review by jkrech — APPROVED** [review]
LGTM the only comment I have is about the decision whether or not we specify a version of not for Pack.xsd PackIndex.xsd.

**Comment by soumeh01** [comment]
> LGTM the only comment I have is about the decision whether or not we specify a version of not for Pack.xsd PackIndex.xsd.

It is a valid point. `Pack.xsd` is already versioned under version tags. The same should be done on `PackIndex.xsd`.
For e.g : https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/e84916a965e1b7578a108b9763bd58b889e11ce6/.github/workflows/toolbox.yml#L77

**Comment by soumeh01** [comment]
> LGTM the only comment I have is about the decision whether or not we specify a version of not for Pack.xsd PackIndex.xsd.

Valid point. `Pack.xsd` is already versioned under version tags. The same should be done on `PackIndex.xsd`.
For e.g : https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/e84916a965e1b7578a108b9763bd58b889e11ce6/.github/workflows/toolbox.yml#L77

I can pick latest tag version i.e. v1.7.37 which points to the latest state of the `PackIndex.xsd`
[https://raw.githubusercontent.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/v1.7.37/schema/PackIndex.xsd](https://raw.githubusercontent.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/v1.7.37/schema/PackIndex.xsd)

**Review by soumeh01 — COMMENTED** [review]
Addressed review comment and [Uses versioned PackIndex.xsd](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/pull/167/commits/4c2c9ddc8e0a2ed9ca6bcdcc0f4759eba4302b36)

**Review by jkrech — APPROVED** [review]
LGTM

**Pull request merged**
